package machine

import (
	"flag"
	"os"
	"testing"

	"github.com/arisros/fate/render"
)

var update = flag.Bool("update", false, "rewrite golden files")

func mustNew(t testing.TB) *Machine {
	t.Helper()
	m, err := New()
	if err != nil {
		t.Fatal(err)
	}
	return m
}

// drive applies events from a fresh session and returns the final result.
func drive(t testing.TB, m *Machine, events ...Event) Result {
	t.Helper()
	res, err := Apply(m, nil, Begin{At: 1})
	if err != nil {
		t.Fatal(err)
	}
	for _, e := range events {
		if res, err = Apply(m, res.Snapshot, e); err != nil {
			t.Fatal(err)
		}
	}
	return res
}

func TestTransitions(t *testing.T) {
	m := mustNew(t)
	cases := []struct {
		name   string
		events []Event
		want   string
	}{
		{"fresh session is idle", nil, Idle},
		{"prompt runs", []Event{Prompt{At: 2}}, Running},
		{"tool start from idle runs", []Event{ToolStart{At: 2}}, Running},
		{"permission waits", []Event{Prompt{}, ToolStart{}, Permission{}}, Waiting},
		{"notification waits", []Event{Prompt{}, NeedsInput{}}, Waiting},
		{"approval resumes", []Event{Prompt{}, Permission{}, ToolEnd{}}, Running},
		{"subagent tool end keeps waiting", []Event{Prompt{}, Permission{}, ToolEnd{Subagent: true}}, Waiting},
		{"unwatched stop is done", []Event{Prompt{}, Stop{}}, Done},
		{"watched stop is idle", []Event{Prompt{}, Stop{Visible: true}}, Idle},
		{"stop with background work keeps running", []Event{Prompt{}, Stop{Background: 1}}, Running},
		{"background resume then stop is done", []Event{Prompt{}, Stop{Background: 1}, Prompt{}, Stop{}}, Done},
		{"stop while waiting is done", []Event{Prompt{}, Permission{}, Stop{}}, Done},
		{"focus clears done", []Event{Prompt{}, Stop{}, Focus{}}, Idle},
		{"focus leaves running alone", []Event{Prompt{}, Focus{}}, Running},
		{"idle prompt ends a turn without stop", []Event{Prompt{}, IdlePrompt{}}, Done},
		{"idle prompt never downgrades waiting", []Event{Prompt{}, Permission{}, IdlePrompt{}}, Waiting},
		{"esc mid-turn repaired by screen", []Event{Prompt{}, ToolStart{}, Screen{Kind: ScreenIdle}}, Idle},
		{"denied permission repaired by screen", []Event{Prompt{}, Permission{}, Screen{Kind: ScreenIdle}}, Idle},
		{"missed dialog found by screen", []Event{Prompt{}, Screen{Kind: ScreenDialog}}, Waiting},
		{"working screen leaves running alone", []Event{Prompt{}, Screen{Kind: ScreenWorking}}, Running},
		{"done agent seen working again", []Event{Prompt{}, Stop{}, Screen{Kind: ScreenWorking}}, Running},
		{"begin resets any state", []Event{Prompt{}, Permission{}, Begin{}}, Idle},
		{"new prompt from done", []Event{Prompt{}, Stop{}, Prompt{}}, Running},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := drive(t, m, c.events...).To; got != c.want {
				t.Errorf("got %s, want %s", got, c.want)
			}
		})
	}
}

func TestSinceMarksStateEntry(t *testing.T) {
	m := mustNew(t)
	res := drive(t, m, Prompt{At: 10}, ToolStart{At: 11}, Permission{At: 20}, ToolEnd{At: 30}, ToolStart{At: 31})
	if res.To != Running || res.Ctx.Since != 30 {
		t.Errorf("got %s since %d, want running since 30", res.To, res.Ctx.Since)
	}
	res = drive(t, m, Prompt{At: 10}, Stop{At: 12, Background: 2})
	if res.Ctx.Since != 10 || res.Ctx.Background != 2 {
		t.Errorf("background stop moved since or lost the count: %+v", res.Ctx)
	}
}

func TestEntered(t *testing.T) {
	m := mustNew(t)
	res := drive(t, m, Prompt{}, Permission{})
	if !res.Entered(Waiting) {
		t.Error("first permission should enter waiting")
	}
	res, _ = Apply(m, res.Snapshot, NeedsInput{})
	if res.Entered(Waiting) {
		t.Error("the notification after a permission request must not re-enter waiting (one sound, not two)")
	}
}

func TestDiagramIsCurrent(t *testing.T) {
	got := "# State machine\n\nGenerated by `go test ./internal/machine -update` from the machine itself.\n\n```mermaid\n" +
		render.Mermaid(mustNew(t).Describe(), render.MermaidOptions{Direction: "LR"}) + "```\n"
	const path = "../../docs/state-machine.md"
	if *update {
		if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("%v (run with -update)", err)
	}
	if string(want) != got {
		t.Error("docs/state-machine.md is stale; run go test ./internal/machine -update")
	}
}

// The hook path builds the machine, restores, sends, and persists once per
// process. The plan's budget for all of it is 1 ms.
func BenchmarkHookPath(b *testing.B) {
	m := mustNew(b)
	res := drive(b, m, Prompt{At: 1})
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		fresh, err := New()
		if err != nil {
			b.Fatal(err)
		}
		if _, err := Apply(fresh, res.Snapshot, ToolStart{At: 2}); err != nil {
			b.Fatal(err)
		}
	}
	_ = m
}
